### PR TITLE
Difficulty setting: Hide Health Potion

### PR DESCRIPTION
**Pull request by Alys**
goes along with https://github.com/HabitRPG/habitrpg/pull/4393

Adds support for a difficulty setting that prevents health potions appearing in the Rewards column.

Note that this is going into the 'difficulty' feature branch, so merging it won't make it live.

### CODE REVIEW

**Comment by crookedneighbor** [comment]
@Alys I see the main repo PR got merged into the difficulty branch, should this one be merged as well?

**Comment by Alys** [comment]
Yes, if it's approved. I'm not going to just assume it's what people want.

**Comment by crookedneighbor** [comment]
Looks good to me :+1: 

Doesn't your PR into the main repo require these to actually work?

**Comment by Alys** [comment]
Oh right, sorry, that's the one you were talking about that's been merged. Yes, I should have merged this already.

**Pull request merged**
