### PR TITLE
Stop using abbreviated names of attributes in UI.

### PR DESCRIPTION
**Pull request by Gaelan**

### CODE REVIEW

**Comment by Gaelan** [comment]
No idea what happened with the test fail. Huh.

**Comment by SabreCat** [comment]
:+1:

**Comment by SabreCat** [comment]
Looks like something unrelated is blowing up. @deilann, do you know what's going on with the "freeRebirth" test?

**Comment by deilann** [comment]
Yes, it fails because I forgot to fix it.

**Comment by deilann** [comment]
Heading over to handle contrib tier!

**Comment by Gaelan** [comment]
`4d286073-0a32-43fd-aad8-40ea713510d7`

**Comment by Gaelan** [comment]
FYI the companion in the main repo is still unmerged.

**Comment by deilann** [comment]
Oh, I've already got it, 'cause I'm magical. ;P

**Comment by Gaelan** [comment]
Never mind, GH doesn't live update open status on mentions.

**Comment by Gaelan** [comment]
@deilann Just out of curiosity how long do these things take to get deployed?

**Comment by deilann** [comment]
Really depends. Sometimes I've seen deploys in 5 minutes. Sometimes the
next deploy isn't for a longer period. I've never seen more than week,
though.

**Pull request merged**
