### PR TITLE
add 17 new shirts, slim+broad

### PR DESCRIPTION
**Pull request by AdrienLemaire**
## Related pull request

[habitrpg/shirts](https://github.com/HabitRPG/habitrpg/pull/1969)

### CODE REVIEW

**Comment by lefnire** [comment]
gonna visit this soon (with your other request). In the meantime, does Github let you re-select which branch you PR to? or do you have to close/reopen? If #2, no worries I'll keep `classes` around till I merge this, then we'll do everything on `develop`

**Comment by AdrienLemaire** [comment]
I'll need to close/reopen the branch. But we can safely merge that one in classes. Images just won't be visibles on the website as long as the branch in habitrpg isn't merged.

**Comment by lefnire** [comment]
Ah, good point. note-to-self on the *_amor_base_0 renames

**Comment by lefnire** [comment]
@Pandoro @lemoness @fuzzytrees, what are your thoughts on these? (see ["Files Changed"](https://github.com/HabitRPG/habitrpg-shared/pull/52/files) tab). Some of them are great: horizon, ocean, purple, zombie (other flat colors were Pandoro's origs). But some of them... I hate saying this, but I'm not so sure they're great quality: convict, cross, redblue, thunder, tropical. Not a diss on your art @Fandekasp, you've very much proven you're a great pixel artists in various threads - I'm just not so hot on these ones, they strike me a bit "shotgun approach". If anyone thinks otherwise, it shows it's just personal preference (so often the case with pixel art) - let's hear some opinions.

Sorry sorry sorry @Fandekasp, you know I'm a huge fan of you!

**Comment by AdrienLemaire** [comment]
@lefnire honestly, I never had any design sense or experience whatsoever, so I'm not surprised, don't be sorry xD

Just note that it should be very easy to allow/refuse shirts by listing/removing them from the [controller lists](https://github.com/Fandekasp/habitrpg/commit/16337c69aaa218144144f4d34f7fd5483892de2b)

Also:

breadstrings

**Comment by lefnire** [comment]
Maybe just my preference after all! (re: breadstrings). 

Ideally, rather than excluding from the JS files we'll move pending / undecided images from `/img/sprites/spritesmith` to `/img/project_files/{designs?}` so they don't get compiled (extra bytes). Eg, `/img/designs/rogue_bows` are complete, but we'll keep them off the master sheet until they're in use.  (PS - can't wait to start adding 'dem bows)

Anyway, no action necessary just yet, will wait to hear back from the artists.

**Pull request merged**
