### PR TITLE
Pet Egg Skeleton sprite correction

### PR DESCRIPTION
**Pull request by meganstrickland**
Skeleton Pet Egg was using an old version of the file with stray pixels.
I've replaced the file with the corrected version.

### CODE REVIEW

**Comment by meganstrickland** [comment]
The skeleton egg still seems to be using the incorrect file in the game. Did I mess this up somehow?

**Comment by deilann** [comment]
No, I'd just imagine it hasn't made it to prod yet. :)

**Comment by meganstrickland** [comment]
Oh, okay. Thanks!

**Comment by lefnire** [comment]
sorry, I missed https://github.com/HabitRPG/habitrpg-shared/commit/cfb762db583ba56a7ed2c2c3f691f685abfc852c with the last launch. Will go out next time (probably along with the notif-restyle merge)

**Pull request merged**
