### PR TITLE
Description for Ski-sassin parka (issue #4424)

### PR DESCRIPTION
**Pull request by Sporax**

### CODE REVIEW

**Comment by crookedneighbor** [comment]
Checking it out now!

**Comment by crookedneighbor** [comment]
@Sporax Merged! Thanks for bearing with the process, you did great!

Can you post your user id here? It can be found in [settings > api](https://habitrpg.com/#/options/settings/api)

**Comment by Sporax** [comment]
Sure, its 9f3d765b-e2d4-411e-aa5b-08e5f6c022b2

**Comment by Alys** [comment]
I'm about to award the tier. You should have it in a minute. Thanks for your help!

**Pull request merged**
