### PR TITLE
Release pets images for compile

### PR DESCRIPTION
**Pull request by deilann**

### CODE REVIEW

**Comment by lefnire** [comment]
@deilann do one of the following:
1. Give me admin rights on your fork of Habit
2. Create your branch on `HabitRPG` repo as a new branch (convention is `deilann/keyimages`)

Then I'll grunt-spritesmith & push

**Comment by deilann** [comment]
I added you as a collaborator. Is that the same thing?

**Comment by lefnire** [comment]
@deilann want me to merge this btw? or is there some other WIP stuff going on?

**Comment by lefnire** [comment]
@deilann you good on this, can we close this PR?

**Pull request closed without merging**
