### PR TITLE
Fixed unit tests

### PR DESCRIPTION
**Pull request by djuretic**
I've fixed the test so the Travis build is back to normal.
I've noticed that the `startOfWeek` helper depends on the locale, if any future feature is going to depend on it, we should revisit it.

### CODE REVIEW

**Comment by djuretic** [comment]
I've also added how to run tests (`npm test`) in the readme file.

**Comment by djuretic** [comment]
Should I create a new pull request targeting the master branch instead of the rewrite branch?

**Comment by lefnire** [comment]
yeah, do this one against master, that's deployed now on beta/production & we'll kill rewrite soon. I added you as a repo admin (shared & web) so I won't be a bottleneck to any contributions you think don't need review per se, so feel free to merge to master as well

**Comment by djuretic** [comment]
Great! 
The only thing preventing me for merging this is here: https://github.com/djuretic/habitrpg-shared/blob/8743e00b623fc96f0fbe3fe2adf63ae301969c1b/script/helpers.coffee#L79
I've added `lastDrop: { date: +new Date, count: 0 }`, is that change safe? I don't know how widely the site relies on `helpers.newUser` defaults.

**Comment by lefnire** [comment]
Looks legit to me! The `helpers.newUser` function is indeed used, kinda inconsistently though. Since moving to Mongoose (from Derby), we're able to rely on its default values for new documents (see https://github.com/HabitRPG/habitrpg/blob/develop/src/models/user.js#L138). However, I don't think we've fully made the switch, so newUser is used from time to time. It's also handy to have around if we ever want to revisit the feature where users can play with the site before registration (they used to be able to, then we had to remove due to maintenance issues). 

Anyway, all looks good. I'd say do another PR to master

**Comment by lefnire** [comment]
i merged to master actually, gonna jump into some tests stuff

**Pull request closed without merging**
