### PR TITLE
Added missing mount texts for drop mounts

### PR DESCRIPTION
**Pull request by crookedneighbor**
Per issue [this issue on habitrpg-mobile](https://github.com/HabitRPG/habitrpg-mobile/pull/297#issuecomment-62307108)

### CODE REVIEW

**Comment by crookedneighbor** [comment]
@paglias Actually, I just figured out a more elegant solution for dealing with this. Hold off on this for now.

**Comment by crookedneighbor** [comment]
@paglias [Fixed it without needing to do this](https://github.com/HabitRPG/habitrpg-mobile/pull/297). It still may be useful to have these though, in case the language has a different name for the pet and mount, like we have a calf and a cow, for instance.

**Comment by SabreCat** [comment]
Sounds like you pursued an alternative path. Closing this pull request--let me know if it's still useful!

**Comment by crookedneighbor** [comment]
I think it could be useful for translations, but it's definitely no longer necessary.

**Pull request closed without merging**
