### PR TITLE
Update npc.json

### PR DESCRIPTION
**Pull request by wc8**
DanielTavern strings for in progress update of tavern.jade
DanielText and DanielText2 strings are left in place so nothing breaks before tavern.jade is updated. They can be deleted later.

### CODE REVIEW

**Comment by wc8** [comment]
Hm... when I changed https://github.com/HabitRPG/habitrpg/blob/develop/views/options/social/tavern.jade it didn't give me a pull request option—it updated right away? 
@deilann / @lefnire I want to make sure I didn't break anything, should I try to revert the changes to to tavern.jade?

**Comment by SabreCat** [comment]
If you edit files using the editor on the GitHub site, it commits the changes immediately. And if you have repo admin rights, you can do that right in the official branch.

**Comment by wc8** [comment]
I reverted the tavern.jade changes for now.

**Comment by crookedneighbor** [comment]
@wc8 or @SabreCat Is this still relevant, or can it be closed?

**Comment by SabreCat** [comment]
This does look like a still-relevant improvement we could make, but it could wait until after retiring habitrpg-shared. The necessary information's documented in the associated issue ticket.

**Comment by crookedneighbor** [comment]
Cool. One change that should be made is that it should all be one variable instead of 5, following [this string as an example](https://github.com/HabitRPG/habitrpg-shared/blob/develop/locales/en/subscriber.json#L69).

**Comment by crookedneighbor** [comment]
We're consolidating the shared repo into the main repo.

The patch url for this PR has been added to this issue: https://github.com/HabitRPG/habitrpg/issues/4536

**Pull request closed without merging**
