### PR TITLE
Calculate ultimateGear achievement in user.ops

### PR DESCRIPTION
**Pull request by colegleason**
This does several things:
- Moves the calculation of the ultimateGear achievement into its on
  function on user.ops.
- Calls user.ops.ultimateGear on user.save instead of on item purchase
- Fixes bug where ultimateGear was not awarded if user wasn't wearing
  their class gear at the time of item purchase.
- Adds content.classes and content.gearTypes which we should start using
  elsewhere.

Fixes habitrpg/habitrpg#2232.

### CODE REVIEW

**Comment by colegleason** [comment]
Totally a bug in this. Let me fix that real quick.

**Comment by colegleason** [comment]
There we go, that sped things up. What do you think?

I also want to start breaking things out of index.coffee if possible. The file is rather unruly.

**Comment by lefnire** [comment]
We actually were originally in multiple files (view helpers, algorithms, etc) and had too many problems with circular dependencies + browserify over the course of a few months. Tried many solutions, just wasn't worth it in the end and had to bring them all into one file. `content.coffee` is the only one I kept intact, but as you can see it redefines some functions (`$w()`, `crit`, etc) due to circ dep issues.

Anyway, i'll check out this PR soon as I can. I might write up a quick algos.mocha.coffee test for it monday just in case, then merge it Monday. Thanks for all the hard work man! Sorry I'm not able to merge / review much this weekend

**Comment by colegleason** [comment]
No problem. And I should really be writing the tests, I just haven't gotten
to it yet.

On Fri, Jan 10, 2014 at 2:50 PM, Tyler Renelle notifications@github.comwrote:

> We actually were originally in multiple files (view helpers, algorithms,
> etc) and had too many problems with circular dependencies + browserify over
> the course of multiple months. Tried many solutions, just wasn't worth it
> in the end and had to bring them all into one file. content.coffee is the
> only one I kept intact, but as you can see it redefines some functions (
> $w(), crit, etc) due to circ dep issues.
> 
> Anyway, i'll check out this PR soon as I can. I might write up a quick
> algos.mocha.coffee test for it monday just in case, then merge it Monday.
> Thanks for all the hard work man! Sorry I'm not able to merge / review much
> this weekend
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/HabitRPG/habitrpg-shared/pull/89#issuecomment-32064716
> .

## 

## Cole Gleason

Student, University of Illinois at Urbana-Champaign
Email: cg@colegleason.com
Website: colegleason.com

**Comment by colegleason** [comment]
Rebased to make this merge-able and squashed all commits into one.

**Comment by lefnire** [comment]
Some concerns about this commit, bear with me:

> Moves the calculation of the ultimateGear achievement into its on function on user.ops.

user.ops are handled specially. If an op is called client-side, it's then replicated server-side. From "Calls user.ops.ultimateGear on user.save instead of on item purchase", this might mean it will get called twice. Sure we don't want it in user.fns?

> Calls user.ops.ultimateGear on user.save instead of on item purchase

A bit concerned that the original 1-liner, now a 30-liner, is called for every possible operation (score, shirt-change, etc). In many cases, "meh" - but in this case, it looks like there's quite a lot getting computed. Sure we don't want this only on purchase?

> Fixes bug where ultimateGear was not awarded if user wasn't wearing their class gear at the time of item purchase.

:+1: 

> Adds content.classes and content.gearTypes which we should start using elsewhere.

:+1:

**Comment by colegleason** [comment]
Sorry, it actually isn't in user save anymore (or shouldn't be). I forgot
to modify the commit message. It should only process on buy.

Not sure about user ops versus fns. I thought we would want it on client
and server

**Comment by lefnire** [comment]
So, `user.fns` and `user.ops` are both available client & server-side. `user.fns` is helper functions on the user object, avail both C&S. But here's what happens with `user.ops`:

Anything inside ops, if it's called on the client it will run the function, then it will send a `POST /user/batch-update {op:OP_NAME}`. The server will receive that op, run the function, and save the user. So for example, `user.ops.score` will score the task in the browser, `POST /api/v2/user/batch-update [{op:"score",params:...}]`, server will run `user.ops.score()` and then `user.save()`.

So if achievements is handled in ops, and in user.save / user.buy, it will get duplicated.

**Comment by colegleason** [comment]
Ok, so if buy is an op, then it is called on client and server when we buy
an item. We only want ultimateGear to run once on client and once on
server, so it should be a fn instead, correct?

IIRC it was only being called once on the server, but that may be because
of the check to see if you already have the achievement.

So, user.fns and user.ops are both available client & server-side.
user.fnsis helper functions on the user object, avail both C&S. But
here's what
happens with user.ops:

Anything inside ops, if it's called on the client it will run the function,
then it will send a POST /user/batch-update {op:OP_NAME}. The server will
receive that op, run the function, and save the user. So for example,
user.ops.score will score the task in the browser, POST
/api/v2/user/batch-update [{op:"score",params:...}], server will run
user.ops.score() and then user.save().

So if achievements is handled in ops, and in user.save / user.buy, it will
get duplicated.

—
Reply to this email directly or view it on
GitHubhttps://github.com/HabitRPG/habitrpg-shared/pull/89#issuecomment-32691968
.

**Comment by colegleason** [comment]
@lefnire, Made the changes and tested.

**Pull request merged**
