### PR TITLE
Typo correction

### PR DESCRIPTION
**Pull request by chmac**
This might be a matter of personal taste, but as a native English speaker (albeit a Scottish one) the flow of this sentence doesn't work. Reward you / damage you. In game terminology, maybe it makes sense, but in life terminology, it doesn't. You won't damage me unless you hack my email, kill my cat, or whatever. Reward / penalize are more usual antonyms.

### CODE REVIEW

**Comment by chmac** [comment]
Awesome, do I get a contributors badge? :+1 Same username... :-)

**Comment by deilann** [comment]
Dunno. @lefnire @colegleason what do you think? I didn't get a level for my
first 3 entry level changes. Was that an oversight or intentional?

(Also, I'd have to have your UUID, not your username.)

**Comment by chmac** [comment]
Guessing that's my user-id in API settings? If so, here it is `0283fcbf-4e83-40cb-8a3c-e0db94fe6b81`.

**Comment by pierreozoux** [comment]
Yeah, sorry, maybe it's my fault, I sold @chmac dream. He was about to commit, and said him, "Yeah, do it, you'll even get a badge" (It was his first day yesterday), and so he spent more time to figure out the right sentence, pull request, and then we were wondering how the badge would come ;)

**Comment by lefnire** [comment]
@deilann oversight (sorry!). You were also a flurry of contributions, so it was hard to keep track of them and we just threw you to 7 ;)

Our thoughts are: 1st code commit, no matter how small, gets ++. Forking, cloning, editing, pushing, sending PR - difficult initial process. As a result, from then on out contribs are more likely to push a second. Each level should be harder (so typos won't cut it for level 2)

Anyway, gotcha sorted @chmac, thanks!

**Comment by deilann** [comment]
kk thnx for the clarification @lefnire!

**Pull request merged**
