### PR TITLE
Corrected placement on rouge_6 weapons

### PR DESCRIPTION
**Pull request by crystalphoenix**
lowered them 2px so that they would be properly aligned with the character

### CODE REVIEW

**Comment by crystalphoenix** [comment]
i hope i did this correctly ^^; github is kinda confusing...

**Comment by lefnire** [comment]
Perfect! You're our first sprite-smither, well done @crystalphoenix ! If your'e feeling adventurous, I have some more repositioning tasks in the queue - would you be down to take a stab?

**Comment by crystalphoenix** [comment]
yay :D i'm glad i did the submitting thing right ^_^
and sure! what needs to be done?

edit: oh! just realized you might not see it unless i put your name in it @lefnire ^^;;

**Comment by lefnire** [comment]
Sorry for the late follow-up on this! Looks like you already found what
needed doing :) You're probably waiting on me to get those bits merged
before moving onto other things .Sorry boot that, will do soon!

**Pull request merged**
