### PR TITLE
Priority multiplier

### PR DESCRIPTION
**Pull request by efim**
view part for https://github.com/HabitRPG/habitrpg/pull/3887

creating difficulty settings for tasks (and etc.) under the priority settings in advanced optinons.
Corresponding ticket - https://github.com/HabitRPG/habitrpg/issues/3556

### CODE REVIEW

**Comment by Alys** [comment]
@efim : Are you able to adjust this PR to remove all of the locales files except `locales/en/tasks.json`?

The way localisation works is that the USA-English text is added manually under `locales/en/` and then all the other locales are updated by translators through Transifex. When a locale does not yet have an entry for new text, HabitRPG's code falls back to using the USA locale file for that piece of text.

**Comment by efim** [comment]
@Alys done. It is probably ok to leave Russian locale since it is already properly translated?

**Comment by deilann** [comment]
No, all the non en (including en_GB) files should not be included, as
translations need to go through transifex and not Github.

**Comment by Alys** [comment]
@efim : If you'd like to work on translations, your help would be much appreciated. The wiki's [Guidance for Linguists](http://habitrpg.wikia.com/wiki/Guidance_for_Linguists) page describes the process.

**Comment by efim** [comment]
@Alys done.

**Comment by crookedneighbor** [comment]
Like I said in your last pr, migrating habitrpg-shared into the main repo. A patch file url has been added to the corresponding main repo PR.

**Pull request closed without merging**
