### PR TITLE
Fix misspelled artist's name in Rooster quest

### PR DESCRIPTION
**Pull request by Algogator**
"extrajordinary" is changed to "extrajordanary"
Issue: #4089
https://github.com/HabitRPG/habitrpg/issues/4089

### CODE REVIEW

**Comment by paglias** [comment]
thanks :) UUID?

**Comment by Algogator** [comment]
User ID right?
172b9cab-23f0-41d1-b591-c372d5acb99c

**Comment by paglias** [comment]
@AnnaPhilips yess, badge awarded

**Comment by Algogator** [comment]
yay :D

**Pull request merged**
