### PR TITLE
Adding two years to the winter gear description

### PR DESCRIPTION
**Pull request by joshbDev**
referencing this https://github.com/HabitRPG/habitrpg-shared/issues/405, I have updated the years to 2013-2014 and 2014-2015 for the winter gear in their respective years.

### CODE REVIEW

**Comment by crookedneighbor** [comment]
Thanks so much! Can you post your user id here? It can be found in [settings > api](https://habitrpg.com/#/options/settings/api)

**Comment by joshbDev** [comment]
for sure! it's 5a07a8f6-100c-447f-9272-d5796326fc93

**Comment by Alys** [comment]
Thanks @thehindenburg! That's been recorded as a contribution towards a tier.

**Comment by joshbDev** [comment]
:+1:

**Pull request merged**
