### PR TITLE
Server side of Rebirth-related fix: don't remove Wolf Eggs upon drops unlock

### PR DESCRIPTION
**Pull request by SabreCat**
Previously, if user had >1 Wolf Egg, performed a Rebirth, then unlocked drops again, they would be reset to 1 Wolf Egg. Now Habit checks to see if they have some Wolf Eggs already, and if so, gives them one instead of setting the quantity to one.

Question for @lefnire / @paglias: I'm being careful about not performing a `++` on an undefined quantity. Is that the right code practice, or will JS turn an undefined into a 1 if the type is number and I add to it?

### CODE REVIEW

**Comment by paglias** [comment]
yes, it's correct to check if it's a number.

```
var a = undefined;
a++
a === NaN (not a number)
```

**Comment by lefnire** [comment]
I hate this stuff, man

**Comment by paglias** [comment]
oh my god, it's horrible

**Comment by SabreCat** [comment]
lolwut? So if I added null to it first, it'd work? xD

**Comment by lefnire** [comment]
@SabreCat [funny you should say "wut"](https://www.destroyallsoftware.com/talks/wat)

**Comment by SabreCat** [comment]
@lefnire Oh Primes. I laughed so hard. My fiancée probably thinks I'm such a dork xD

**Pull request merged**
