### PR TITLE
Adding custom backer items from Leslie.

### PR DESCRIPTION
**Pull request by Shaners**
Sprite sheet for custom backer gear, created by Leslie.

Not sure what the mechanics are going to be to give the backers access to these items so was unsure where to put the CSS positioning stuff.

### CODE REVIEW

**Comment by lefnire** [comment]
shnazzy! so only 4 of them pulled through eh?

**Comment by Shaners** [comment]
I think only 3 responded, the rest will be getting that helmet. Maybe seeing a new random piece of gear no one else has will prompt them to respond. Or can use them as a playground to test out new gear ideas.

**Comment by lefnire** [comment]
oh, smart with the "fallback item". Ok, I'll start brainstorming an implementation strategy.

**Comment by Shaners** [comment]
Perhaps perma-equiped with custom stat bonuses (so not available in the shop) and in the future an ability to reskin but keep elevated stats. So they always have this item equipped no matter what with the highest stats plus a bonus. It'd power level them at lower levels but that's kind of the point of the gear me thinks.

-Shane

**Pull request merged**
