### PR TITLE
Add Travis build status to Readme

### PR DESCRIPTION
**Pull request by djuretic**

### CODE REVIEW

**Comment by lefnire** [comment]
well check this out in a bit. What's your UUID real quick? you need some contrib swag

**Comment by djuretic** [comment]
UUID: 1c462a01-964a-4a69-b557-4ed6cd1b872d

**Comment by djuretic** [comment]
Wow, thanks a lot!

**Comment by lefnire** [comment]
Fantastico!

**Comment by djuretic** [comment]
:)

**Pull request merged**
