### PR TITLE
Update content.coffee to change "Cloth Armor"

### PR DESCRIPTION
**Pull request by deilann**
Changes Cloth Armor to "Plain Clothing" for better consistency and sprite representation.

### CODE REVIEW

**Comment by deilann** [comment]
https://github.com/HabitRPG/habitrpg/issues/2402

**Comment by colegleason** [comment]
LGTM

**Comment by colegleason** [comment]
@deilann What is your UUID?

**Comment by deilann** [comment]
e7b5d1e2-3b6e-4192-b867-8bafdb03eeec

**Pull request merged**
