### PR TITLE
Fix for issues #3573 - Correction for strange pixel on gems.

### PR DESCRIPTION
**Pull request by robeden**
This corrects two pixels on each version of the gem:
- Missing dark grey pixel at the top
- Stray light grey pixel in the 11:00 position that should be transparent (difficult to see outside an editor)

### CODE REVIEW

**Comment by deilann** [comment]
waiting on permissions verifications. :)

**Comment by robeden** [comment]
@deilann - I sent the email. Let me know if you didn't get it.

**Comment by deilann** [comment]
I'm not the one who gets the email, is the issue. So I need a verification
from @lemoness. Or possibly @veeeeeee?

**Comment by veeeeeee** [comment]
Received and confirmed. (FTR, all three cofounders get the email.)

**Comment by deilann** [comment]
Ah, good to know!

**Pull request merged**
