### PR TITLE
New Red Hair Option

### PR DESCRIPTION
**Pull request by Shaners**
Also fixed a few pixel grid alignment issues.

### CODE REVIEW

**Comment by lefnire** [comment]
i'll push to dev. may be a bit before pushing to master, since we'll want to cut a new mobile release too & we'll probably want a handful more changes in mobile before pushing

**Comment by Shaners** [comment]
Sounds good! Beta web will get this soon though? Edge users need their edge features!

**Comment by lefnire** [comment]
pushing to beta now, 5m

**Comment by lefnire** [comment]
on prod too, but you can't select the hair. eh, maybe we should just roll with it if we don't have a reason to cut a new mobile after a few days

**Comment by Shaners** [comment]
Just noticed that the female red hair is missing pixels. This will need to be fixed so maybe avoid pushing to mobile until then.

**Pull request merged**
