### PR TITLE
Add .travis.yml

### PR DESCRIPTION
**Pull request by djuretic**
For Travis CI integration.

### CODE REVIEW

**Comment by paglias** [comment]
I think node 0.10 only is ok as habitrpg is set to run on it

**Comment by djuretic** [comment]
Ok, I've removed node 0.8

**Comment by djuretic** [comment]
Hmm, I guess I'll need to add that file to the master branch, not the rewrite branch. 
Don't merge this pull request yet.

**Comment by paglias** [comment]
Maybe we could wait until rewrite is moved to master

**Comment by lefnire** [comment]
we can merge to rewrite, it just won't be used by github + travis until it's merged to master (right?)

**Comment by djuretic** [comment]
@lefnire Yes. But you can merge this to rewrite and then  cherry-pick this commit to master if needed.

**Comment by lefnire** [comment]
will do!

**Comment by djuretic** [comment]
Good! Don't forget to visit https://travis-ci.org and enable the repository there.

**Comment by lefnire** [comment]
Ok, I enabled for habitrpg-shared. Should I also enable for mobile & web?

**Comment by djuretic** [comment]
No, let's just start with habitrpg-shared.

**Pull request merged**
