### PR TITLE
Moved slim Umbral Armor up one 3x3 pixel block, so it matches other rogue armor.

### PR DESCRIPTION
**Pull request by PeterHatch**
It was lower than other rogue armor, and showing a couple of pixels of the shirt underneath.

### CODE REVIEW

**Comment by deilann** [comment]
Can I get a screenshot again? Before and afters of these really help my brain.

**Comment by PeterHatch** [comment]
Here's a screenshot of the fixed version:
slim umbral armor fixed

And the original version:
slim umbral armor original

**Comment by lefnire** [comment]
@lemoness , thoughts?

**Comment by lemoness** [comment]
Yep! That was a weird alignment error that just never got fixed.

**Comment by deilann** [comment]
I know I said 4 small PRs, but some of these are more medium sized than small and the class bonus thing was vexing a lot of people, so welcome to level 4 @PeterHatch !

**Comment by PeterHatch** [comment]
Thanks!

**Pull request merged**
