### PR TITLE
add texts for new moderator/guardian level, and "staff" and "tier"

### PR DESCRIPTION
**Pull request by Alys**
see https://github.com/HabitRPG/habitrpg/pull/3826 for details and screenshots

### CODE REVIEW

**Comment by deilann** [comment]
a passed build...

`faints`

**Comment by lefnire** [comment]
lord almighty

**Comment by lefnire** [comment]
@Alys you're close to all your various PRs related to this one feature. If you feel confident in the batch, and we devs are lagging, don't hesitate to merge

**Comment by Alys** [comment]
But then how can I blame someone else if it all goes horribly wrong? :)

**Comment by deilann** [comment]
You can still blame me, if you want.

Or Ben.

**Comment by lefnire** [comment]
Poor Ben...

**Comment by deilann** [comment]
It's what he gets for sleeping in the box last night, and not with Alys.

**Comment by Alys** [comment]
So, yeah... anything that breaks is all Ben's fault:
Ben

**Comment by SabreCat** [comment]
This thread was much more amusing before I was certain Ben was a cat.

**Pull request merged**
