### PR TITLE
Pull req: Clarifying spell effects on attributes

### PR DESCRIPTION
**Pull request by gitte-k**

### CODE REVIEW

**Comment by gitte-k** [comment]
@Alys Done :) Still newish to git, but it's luckily pretty simple and well documented :)

**Comment by crookedneighbor** [comment]
:+1:

**Comment by Alys** [comment]
Thank you @lacrimae! If you tell me your [unique user ID](https://habitrpg.com/#/options/settings/api), I will give you a contributor tier.

**Comment by gitte-k** [comment]
@Alys Thanks a bunch! It's 3ecf07b0-4bea-4e6b-b0a0-4cb6e29a5699

**Comment by Alys** [comment]
Tier++

ref: https://github.com/HabitRPG/habitrpg-shared/issues/380

**Pull request merged**
