### PR TITLE
Add golden paw graphic for missing but obtainable rare pets.

### PR DESCRIPTION
**Pull request by Shaners**

### CODE REVIEW

**Comment by Shaners** [comment]
Is master the appropriate branch tp PR this to?

**Comment by lefnire** [comment]
yeah, let's start merging everything to master instead of rewrite now. rewrite will be deleted once we launch chal

**Comment by lefnire** [comment]
(ps, feel free to merge as you see fit. be bold, your stuff is pure gold)

**Comment by Shaners** [comment]
Aye aye! Hopefully we'll never need pixelated poop then my stuff would be pure shi...

**Comment by lefnire** [comment]
you're missing a 't' - I SAID BE BOLD

**Pull request merged**
