### PR TITLE
Redid all shop images.

### PR DESCRIPTION
**Pull request by PeterHatch**
Reworked all shop images to always be 2x2 pixel blocks (2/3rds the
original size), never scaled unevenly.

Also went through and touched up every image if needed, removing
transparent pixels for the hand on each weapon, removing arm outlines
from armors that don't cover the arm, and so on.

Also reorganized the shop files - in gear, each directory has its own shop subdirectory (as events/spring already did). The few remaining images were moved from gear/shop to shop.

Screenshots of the new version:
new healer
new rogue
new special
new warrior

And here's the current version:
old healer
old rogue
old special
old warrior

### CODE REVIEW

**Comment by deilann** [comment]
Ahhhh this makes me so happy.

**Comment by lefnire** [comment]
@PeterHatch could you do a rebase & force-push? Looks like some conflicts cropped up since when you submitted the PR. Sorry I didn't merge sooner, IIRC I've done some sizeable updates which will have caused folder organization conflicts.

**Comment by PeterHatch** [comment]
Okay, did the rebase & force-push.

Also did a little bit more re-organizing, and updated the shop images for the mystery_201403 items.

**Comment by deilann** [comment]
I pressed the button!

**Comment by PeterHatch** [comment]
:grinning:

**Comment by deilann** [comment]
This seems like it was a huge effort! I'm calling it at least half of level five, 'cause wow!

**Comment by lemoness** [comment]
Hey@PeterHatch! Thanks for all your work on this. Since you're doing a lot of art, would you mind shooting me an email (leslie@habitrpg.com) so that I can send you the Art Permissions form? We'll need you to sign it before we can use any of these art assets. Also, if you have any more art pieces that you're making, take them to the Art Trello first so that I can keep track of them :)

**Pull request merged**
