### PR TITLE
Translated front.json from English to Bulgarian

### PR DESCRIPTION
**Pull request by astroslav**
I believe I'm supposed to leave my user ID in here, but I'm not sure which ID that's referring to so I'll just leave my github one? ssupermario? It's the same one for HabitRPG anywho.

### CODE REVIEW

**Comment by paglias** [comment]
Thanks @ssupermario ! When you're done with other files you can add them to this PR. The user id is your one on Habit, you can find it in Options -> Settings -> API

**Comment by astroslav** [comment]
Found the ID code thing! 939751e2-d0c7-4d04-a9af-466a7967e421

I have just one question. When I translate the other ones, do I just click on that pull request button again or do I have to do something else to add them to this PR?

**Comment by paglias** [comment]
I never did it this way but I think that clicking the pull request button is enough

**Comment by astroslav** [comment]
Alright. Thanks! :+1:

**Comment by astroslav** [comment]
Oh, I actually have one more question. I noticed that you made changes to the original files where you added in a couple of things. When I tried to fork those new files, it doesn't change on my side. How exactly do I "refresh" my files so I can translate the most current file?

**Comment by paglias** [comment]
If you are using the web interface i sincerely don't know because I never
used it. Searching on google I found this
http://webapps.stackexchange.com/questions/28998/how-do-you-update-a-github-repo-fork-in-the-web-interfacebut
couldn't check if it actually works.

Anyway always follow the english locale: I checked your fork and the only
strings you're missing are
https://github.com/HabitRPG/habitrpg-shared/commit/c39d2a8a1384cb1c608cb7069cfa9cb4712174d6#diff-95763aad3ec44c8df8c68580a86cfe34R7,
if you can't get an updated fork, then add those three strings manually to
the bulgarian locale

2014-02-09 19:38 GMT+01:00 ssupermario notifications@github.com:

> Oh, I actually have one more question. I noticed that you made changes to
> the original files where you added in a couple of things. When I tried to
> fork those new files, it doesn't change on my side. How exactly do I
> "refresh" my files so I can translate the most current file?
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/HabitRPG/habitrpg-shared/pull/139#issuecomment-34581865
> .

## 

Matteo Pagliazzi - paglias.net

**Comment by paglias** [comment]
(I know the actual method for translating is quite a mess when things get
updated on the english side, we're trying to find a better solution)

2014-02-09 20:28 GMT+01:00 Matteo Pagliazzi matteopagliazzi@gmail.com:

> If you are using the web interface i sincerely don't know because I never
> used it. Searching on google I found this
> http://webapps.stackexchange.com/questions/28998/how-do-you-update-a-github-repo-fork-in-the-web-interfacebut couldn't check if it actually works.
> 
> Anyway always follow the english locale: I checked your fork and the only
> strings you're missing are
> https://github.com/HabitRPG/habitrpg-shared/commit/c39d2a8a1384cb1c608cb7069cfa9cb4712174d6#diff-95763aad3ec44c8df8c68580a86cfe34R7,
> if you can't get an updated fork, then add those three strings manually to
> the bulgarian locale
> 
> 2014-02-09 19:38 GMT+01:00 ssupermario notifications@github.com:
> 
> Oh, I actually have one more question. I noticed that you made changes to
> 
> > the original files where you added in a couple of things. When I tried to
> > fork those new files, it doesn't change on my side. How exactly do I
> > "refresh" my files so I can translate the most current file?
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHubhttps://github.com/HabitRPG/habitrpg-shared/pull/139#issuecomment-34581865
> > .
> 
> ## 
> 
> Matteo Pagliazzi - paglias.net

## 

Matteo Pagliazzi - paglias.net

**Comment by colegleason** [comment]
@paglias What if when we wanted to add an English string, we ran a script that added it to locale/*/{filename}.json? I could probably write that up if you wanted.

**Comment by marcelosizer** [comment]
@paglias @colegleason transifex can do something like that right? There's a github repo from transifex couldn't we just use it to keep everything updated and free?

**Comment by paglias** [comment]
Their  repository I think is there because they have some open source code
but I don't think we can install transifex on our server or something like
that. I sent them an email applying for the free service for open source
project, I hope they'll answer tomorrow. Using transifex updating the
English file will automatically update all the other languages,
invalidating old strings when needed.

**Comment by paglias** [comment]
@ssupermario Hi!

We moved translations to Transifex, a web service for managing translations, no more Pull Requests, conflicts and Github. It's going to make life a lot easier for you.

I already uploaded there the two files you sent here and I'm going to close this PR.

You can register there to partecipate. Let me know if you have any problem!

https://www.transifex.com/projects/p/habitrpg/

**Pull request closed without merging**
