### PR TITLE
Split main.json

### PR DESCRIPTION
**Pull request by marcelosizer**
Fixes #2582, #2572 and splits the main.json file into many others.

@paglias could you check this please?

### CODE REVIEW

**Comment by paglias** [comment]
@Sinza- merged, what are the strings in limbo.json? They seems to be needed, where should I put them?

**Comment by marcelosizer** [comment]
@paglias the strings in limbo.json were strings that I tried to grep but got nothing. I left them there as I wasn't sure they were removed. If any of them are used you can put on their respective json file. I'm finishing the subscriber.json and gonna open a PR soon.

**Comment by paglias** [comment]
Ok, I've moved the ones used in their files and removed the other ones

**Comment by marcelosizer** [comment]
I'm gonna add #115 strings to the PR with the subscriber strings.

**Comment by paglias** [comment]
I added them when merging this PR!

**Comment by marcelosizer** [comment]
So I'll only add subscriber strings. =p

**Pull request merged**
