### PR TITLE
change "goal" to "task" throughout Tour

### PR DESCRIPTION
**Pull request by Alys**
In productivity contexts, "goals" tend to be large, long-term projects, whereas "tasks" are smaller actions, and I think "tasks" better matches HabitRPG's features. 

"task" is used in Habit's code in many places. The wiki uses "tasks" rather than "goals" throughout, although admittedly that was a fairly recent change. Many players use "task" when describing habits/dailies/to-dos in the Tavern.

### CODE REVIEW

**Comment by deilann** [comment]
:thumbsup:

I support this change.

**Comment by thepeopleseason** [comment]
:+1:

**Comment by lefnire** [comment]
conflicts

**Comment by Alys** [comment]
I'll re-do this one from scratch using the command-line tools instead of the web interface. It will be good practice.

new pull request: https://github.com/HabitRPG/habitrpg-shared/pull/210

**Pull request closed without merging**
