### PR TITLE
Update communityGuidelines.json

### PR DESCRIPTION
**Pull request by lioman**
I think there is at least one word missing. (I' ve added two)

### CODE REVIEW

**Comment by Alys** [comment]
Hi @lioman!  "All things [noun]" is a phrase that means, roughly, "all things related to [that noun]". For example, see point 1.5 in http://www.oxforddictionaries.com/definition/english/thing but it might not be in common use.

@lemoness, this is a proposed change to the Community Guidelines, so we won't merge or close without your say-so.

**Comment by lioman** [comment]
That is something that you can not do with a noun in German, that for I stumbled over the sentence while I try to translate it in transifex. And I did not know that you can do this in English. With HabbitRPG it sound a little bit "bumby". The example sentences under point 1.5 are clearer

**Comment by Alys** [comment]
You can definitely change the wording as needed in translations!

"Bumby" is a word that I don't know. :) What does it mean?

**Comment by lioman** [comment]
If you drive over a street with many holes in it - it is bumby

**Comment by Alys** [comment]
Oh! I should have realised. It's spelled "bumpy" though. :) Your comment makes sense.

**Comment by lioman** [comment]
That was a typo. I should not comment on language issues when I'm tired and should learn for exams. I push the "-"-button on HabitRPG

**Comment by lemoness** [comment]
Maybe "all things related to HabitRPG"?

**Comment by deilann** [comment]
I don't think that's necessary. It's pretty well understood by English
speakers, and translators will translate it appropriately in their language?

**Comment by crookedneighbor** [comment]
I agree with @deilann, it's a common idiom in English.

**Pull request closed without merging**
