### PR TITLE
highlight the current username

### PR DESCRIPTION
**Pull request by negue**
Example:
Mention Underline

Once merged, we can close: habitrpg/habitrpg#3293 habitrpg/habitrpg#3114

### CODE REVIEW

**Comment by lefnire** [comment]
SGTM

**Comment by ghost** [comment]
Could anyone please see is it working now for you? I don't seem to see it in firefox.

**Comment by crookedneighbor** [comment]
Works for me: 

screen shot 2015-04-30 at 8 45 39 am

**Comment by crookedneighbor** [comment]
That screenshot was taken in Firefox, from my test account "haxfred"

**Comment by ghost** [comment]
Thank you, @crookedneighbor ! 
Now I see the difference. 
I meant a bit different thing in https://github.com/HabitRPG/habitrpg/issues/3293
The thing is, you know your nickname and the whole post that addresses you is highlighted. But what is sometimes difficult - that's to see the nick names of other people:
http://oi58.tinypic.com/11qtikp.jpg
Or was https://github.com/HabitRPG/habitrpg/issues/3293 closed because of difficulties in implementation?

**Pull request merged**
