### PR TITLE
Add Contributor Only Assets

### PR DESCRIPTION
**Pull request by Shaners**
Hydra Pet Art and CSS
Shield Art
Weapon Art
Shop Sprites

Missing Equipment CSS, testing the equipment. (Pet tested.)

### CODE REVIEW

**Comment by lefnire** [comment]
awesome man! did you mean to close without merging? want me to merge?

**Comment by lefnire** [comment]
yeah, this is great - i'm gonna merge, then i'm going to bring habitrpg-shared back to `master`

**Comment by Shaners** [comment]
Looked like there were some conflicts so I was just going to rebase then do another request. To make things cleaner.

**Comment by Shaners** [comment]
Totally up to you though!

**Comment by lefnire** [comment]
oh it's just dist/*. built files will almost always be in conflict, I usually just run grunt again and use the new built files as the merge-resolution. Ok, pushing to master

**Comment by Shaners** [comment]
@lefnire was this already pushed to master?

**Comment by lefnire** [comment]
not yet i don't think, I'm curating the necessary bits in [the Trello checklist](https://trello.com/c/wkFzONhE/277-contributor-gear) (add any I'm missing) then I'm going to merge & code these all into a new branch once I hit it

**Comment by lefnire** [comment]
Oh i'm stupid, it was merged already

**Comment by Shaners** [comment]
@lefnire if this is in then https://github.com/HabitRPG/habitrpg/pull/1649 can be merged as well. Not sure how long the contributor stuff is going to take to finalize but I figure may as well get that golden paw up there as soon as possible!

**Comment by lefnire** [comment]
done & done

**Comment by lefnire** [comment]
oh wait, not done & done.  gotta do something real quick then will do

**Pull request closed without merging**
