### PR TITLE
Fix Backer and Contributor armor, add misc assets, archives certain files

### PR DESCRIPTION
**Pull request by Shaners**
Please test this first. It should work but I ran out of time to test (need sleeps.)

### CODE REVIEW

**Comment by Shaners** [comment]
Boo there is an extra commit here, @lefnire would you prefer this split up into separate PRs? For stuff non-contrib related is it better to just PR to master since develop is gone?

I may be able to test this evening but have plans so will see if I can get to it.

**Comment by lefnire** [comment]
naw, this is perfect. This a solid PR my friend! Gonna test it today

**Comment by lefnire** [comment]
Crystal set's a bit off:
1) [sword](http://gyazo.com/3bd7ed2e735f9240dc465802af8d1d6c)
2) [armor](http://gyazo.com/d9e32a83c5add15f515fda55ea0cafd3) (down a few pixels? actually looks fine with helm, but less without)
3) I think shade might have a tad of the same issue as #2. Mucking around, they only have this issue when it's _just_ armor, no other gear. With all gear, everything looks perfect - and in fact, when I adjust things up it doesn't fit the face - so may be you have it right, I'll stop speaking where I don't know shit lol

Just in case, to test locally you'll want to run in your local Mongo:
`db.users.update({_id:YOUR_ID},{$set:{'backer.tier':800, 'admin.contributor.level':8}, $addToSet:{'items.pets':'Wolf-Cerberus', 'items.pets':'Dragon-Hydra'}})`

**Comment by Shaners** [comment]
Ugh I broke something on my local, backer gear not showing up on avatar at all for some reason. Really wanted to finish this off but now I have to go get drunk :beers:

**Comment by lefnire** [comment]
Ugh, getting drunk is the worst! I'm so sorry!

**Comment by lefnire** [comment]
Another thing @Shaners is I found `grunt` doesn't always replace dist/css, so sometimes I have to delete dist/css and re-run grunt. Works fine for dist/js. And also, have to manually restart the server after running `grunt` on habitrpg-shared - seems `grunt-nodemon` won't rebuild the linked css. I could be doing something totally wrong on my end, but just something to try if you're getting unexpected results

**Comment by paglias** [comment]
@lefnire I thought I fixed the grunt thing not reloading css when I switched to manifest.json, try running `grunt run:dev`

**Comment by lefnire** [comment]
Ah, I'll give it a gander!

**Comment by lefnire** [comment]
sorry for the delay @Shaners, I know you're probably cleaning up shop. Hang on if you can for just a bit more to when I can merge this

**Comment by lefnire** [comment]
This has been merged into `classes` branch. Thanks again @Shaners! Miss you buddy :(

**Pull request closed without merging**
