### PR TITLE
Make first drop be a random egg instead of a Wolf egg

### PR DESCRIPTION
**Pull request by marcelosizer**
Before @colegleason fixed the `randomVal` function I was getting a tiger egg instead of a wolf egg but after that this part of `randomDrop` function started working as it should so the random first egg drop is working. Some issues though:
- I don't know if the index.coffee file is ok or not;
- Couldn't make the file views/shared/modals/drops.jade work as intended, showing the dropped egg. (@paglias was replacing strings on that file and it seemed so easy that I had to give it a try, half of it is working =p) I tried this and some other variants but it just doesn't show the egg image/text/notes:

``` jade
p
  span.item-drop-icon(class='Pet_Egg_{{user.items.eggs[firstDrop.key]}}', style='margin-left: 0px')
  | You've unlocked the Drop System! Now when you complete tasks, you have a small chance of finding an item. You just found a
  strong  {{user.items.eggs[firstDrop.text]}} Egg
  | ! {{user.items.eggs[firstDrop.notes]}}.
```

### CODE REVIEW

**Comment by colegleason** [comment]
Is firstDrop available in the scope of the jade file? I imagine that is the issue. For any variable to be accessible in the template, I think it must be attached to `$scope`.

Not sure what you mean by index.coffee being ok or not. It looks fine to me.

**Comment by marcelosizer** [comment]
No, it's not available and I'm afraid I don't know how to do that. Should it be something like adding `user._tmp.firstDrop = firstDrop;` to habitrpg-shared.js and index.coffee and then creating a function on notificationCtrl.js?

**Comment by marcelosizer** [comment]
I believe I've done it.

@colegleason can you check [habitrpg #2482](https://github.com/HabitRPG/habitrpg/pull/2482) to see if it's ok?

**Comment by marcelosizer** [comment]
I've just messed something up.

**Comment by marcelosizer** [comment]
Instead of fixing I'm screwing things up even more. How can I remove those commits? Should I close this PR and open a new one?

**Comment by marcelosizer** [comment]
I don't know what I did here, gonna close and open a new PR.

**Comment by colegleason** [comment]
Github will add commits to the PR that differ between your branch and what you are trying to merge into. I can help you fix your branch if you need. You probably just need to rebase.

**Comment by marcelosizer** [comment]
@colegleason I tried to rebase, but each time it got worse. Created a new branch and gonna make a new PR. I still don't know what I should do when the repository gets updated. Usually I do:

```
git fetch upstream
git rebase upstream/develop
```

But sometimes things get messy when the local branch diverges from the remote branch. What should I do then?

**Comment by colegleason** [comment]
I think that would only happen when develop has been force pushed? In that
case you could use git rebase -i to remove the double commits.

On Mon, Jan 20, 2014 at 11:18 AM, Marcelo Sizer notifications@github.comwrote:

> @colegleason https://github.com/colegleason I tried to rebase, but each
> time it got worse. Created a new branch and gonna make a new PR. I still
> don't know what I should do when the repository gets updated. Usually I do:
> 
> git fetch upstream
> git rebase upstream/develop
> 
> But sometimes things get messy when the local branch diverges from the
> remote branch. What should I do then?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/HabitRPG/habitrpg-shared/pull/97#issuecomment-32778856
> .

## 

## Cole Gleason

Student, University of Illinois at Urbana-Champaign
Email: cg@colegleason.com
Website: colegleason.com

**Comment by marcelosizer** [comment]
I'll try that next time, thanks.

**Pull request closed without merging**
