### PR TITLE
Add haveUnallocated string

### PR DESCRIPTION
**Pull request by betaveros**
In conjunction with https://github.com/HabitRPG/habitrpg/pull/4112

### CODE REVIEW

**Comment by paglias** [comment]
I forgot to merge this, can someone merge it because I can't from mobile

**Comment by paglias** [comment]
@Alys

**Comment by Alys** [comment]
@paglias I'm looking at it now. I'm checking the tests and merge conflicts before I merge.

**Comment by paglias** [comment]
The tests are the one that we have to fix, nothing important
Il 09/ott/2014 09:54 "Alice Harris" notifications@github.com ha scritto:

**Pull request merged**
