### PR TITLE
Redone healer shields, start on new bang colors

### PR DESCRIPTION
**Pull request by crystalphoenix**
new healer shields per https://github.com/HabitRPG/habitrpg/issues/943#issuecomment-30950025

start on new bang colors for bangs 1 and 2. placed them in a separate folder to better keep track of them.

### CODE REVIEW

**Comment by crystalphoenix** [comment]
@lefnire @lemoness @mariahm i'm not all too sure what to name each of the colors...
the new red color i've named "darkred" for now. would it be better to name the existing red color to "naturalred" and have this just be "red" since the related colors in the set are just the basic rainbow colors?

i've named all the pastel colors ccCOLOR since the pink and blue have been grabbed from the pet cotton candy colors... do you have a better naming scheme...? ^^;;

**Comment by lemoness** [comment]
Hm, maybe the existing natural red should be "ginger"? 

The ccCOLOR works okay for me, or you could do pastelCOLOR.

**Comment by lemoness** [comment]
Also, now you guys know that there are the new hair colors that people can buy - would you be willing to recolor your new hairstyles with the four winter event colors?

**Comment by ghost** [comment]
@lemoness 
I don't mind at all, but I don't have a very good view of what they look like--I've got half a bang showing up in habit-is there a sheet I can pull colors from & get a better look at the patterns?
--Also, now that I'm trying to pull the colors off the hairstyles, its also looking like I'm not getting true colors. Some of the pixels have two different values.(I haven't bought this set)

@crystalphoenix 
for the positioning--if they're arranged position wise in a sheet, is that a help at all, or not worth bothering, also: are there any pieces that you still need tweaked & split? as for naming, yeah, I've just been calling the pastel ones ccColorname, I personally don't care, so whatever makes organizing best, don't worry about stepping on my toes, you can rename as you please :)

**Comment by crystalphoenix** [comment]
@mariahm you can find the files for the new colors here: https://github.com/HabitRPG/habitrpg-shared/tree/develop/img/sprites/spritesmith/hair
they're named candycane, frost, holly, and winternight. 

if it's extra work for you to position them just right in your sheets, it's not something you have to go through :)
i try to double check all of my positioning anyways, so that could save you some work. but keeping colors together will be helpful either way ^_^

the only ones i'm not too sure on are your new bangs since they don't have an outline that lines up with the bald profile. if you can show me an example of one of them and how they should look on a head, i can work off that ^_^

@lemoness i guess i'll change the current red to ginger and stick with ccCOLOR. 
when i'm able to get around to doing more... busy week, so we'll see ^^;;

**Comment by lemoness** [comment]
No rush! We won't be able to roll them out until January or February anyway
:)  Enjoy your week!

**Comment by ghost** [comment]
@crystalphoenix 
I recolored the new hair, I'm assuming there's already versions of everything that's in effect right now.
I've also attached a piece on the side with the two bangs without the regular outline overtop of a head.
winterhair
I only did the Holly on the bangs as it was just too busy looking otherwise.

**Comment by lefnire** [comment]
@crystalphoenix you're tearing it up! thank you so much for jumping into spritesmith, that stuff takes me so long to do. I'm gonna test locally to make sure everything's positioned properly, then I'll merge

**Comment by lefnire** [comment]
Things look good! Some bits: 
- Do me a favor, move `img/sprites/spritesmith/hair color wips` to `project_files/sprites/hair_color_wips`. Goal to keep WIPs outside of spritesmith till they're done, since they'll get compiled there.
- Rogue armor, healer sheilds - perfecto! (I've been hoping someone would come along and fix the rogues, was on my bucketlist)
- Started to write that you have a lil' artifact above hair_bangs_2_rot.png, but realized - that's flies, isn't it? If so, √
-  Healer shields need shop_\* equivalents. I think they're all under 40x40, so you can just re-canvas them with the shield in the center as 40x40, then paste them over the current (`img/sprites/spritesmith/shop`)

Anyway, I can do all of these if you want. Just wanted to bounce them off you, and also wasn't sure if you wanted me to keep this ticket open since sounds like your'e still in progress

**Comment by ghost** [comment]
I've gone and lined everything up on a 90x90 grid, over the avatar, the lines are 2 pixels wide, and each 90x90 grid has a single pixel bordering the inside of it. Hope that makes life a little easier.

I guessed on the position for the mustaches and beard, so those might be off.

The "rot" artifact: I didn't put any flies in, and I can't find an artifact on my files, so unless @crystalphoenix changed that, its not meant to be there.

A couple tweaks if you haven't hit these parts yet:

I tweaked the zombie a bit (and included both) the tweaked version has yellowed eye whites, like the pets. Only the bangs and facial hair have the modified eyes.

I included another hair style: this is basically the combination Big Afro and the bangs without a border, I don't recommend including all three, its redundant, but choosing between the border-less bangs and the combo piece. The Afro on its own has a very different look when paired with the other bang styles. 

all-hair

**Comment by crystalphoenix** [comment]
@lefnire feel free to take care of all of the points you've pointed out since it'll be a while till i have the time to do more pixel things :)

hair_bangs_2_rot.png really does have artifacts that i've missed ^^; they're not flies, so feel free to delete them.
i'll keep in mind to put all new sprite things in the project_files/sprites folder in the future ^_^

can i propose that there be a hair_top layer to go on top of the hair_bangs layer? i think it may solve the afro problem and allow for hair pieces that break the head outline on the bangs when combined with them. for example placing the mohawk, the center bun, or a modified big afro on top of the bangs?  from what i can see, the borderless bangs are a trimmed down version of the little curly bangs, so if the top part is covered by the big afro, it would essentially be the same. 
hmm... i hope i'm explaining this right, let me know if i'm not and i'll try again ^^;; 

@mariahm that's awesome ^_^ thanks for doing the recolors too~

**Comment by ghost** [comment]
re Afro & bangs: The curly bangs were actually made from the unoutlined one, in case the unoutlined one was thrown out. The afro has the usual black outline, and the one set of bangs cover that up, so its a seamless piece. I can rework them however ends up best though :) If I take the "outline" layer from the bangs and include it in the afro, and it ends up as an "over bang" layer it'll alter the way the other bangs look under it as well, and it should look OK.

The Mohawk & combo-afro would easily work as a bang layer, in fact the mohawk should be a bang layer, it'll look bad with them. But the top-knot & the spikes that @crystalphoenix designed work way better over top of the bangs. It would also mean I could get rid of the unoutlined bang design.

My biggest worry with adding more layers is speed--I have no idea how it would impact that. Habit RPG is already a little sluggish (I also never expected all my haircolors to make it in).

And @crystalphoenix  thank you for the technical help, or these would just sit in limbo, as I have no idea what I'd be doing with them :)

**Comment by lemoness** [comment]
About that - I think we're going to pass on the ice hair (too similar to
the frost hair), but would like to keep the others. HOWEVER! I would like
to break p their release, maybe to do more limited edition things! I was
thinking, for example, that the pastel hair colors would work nicely with a
spring event.

Do you have opinions about what groups you would like to be released
together, or colors? In general, we've been doing around 5ish at a time,
but that could absolutely change.

**Comment by crystalphoenix** [comment]
@mariahm ah, your concerns about speed isn't something i thought of. @lefnire do you have thoughts on the potential additional layer?

@lemoness i'll remove the ice color when i continue through them all :)
as for possible groupings maybe the following?

basic dyes (red, blue, yellow etc.) - 6 colors
pastel versions of the above - 6 colors
other pet based colors + fire (so zombie variants, desert, fire) - 6 colors
rainbow  - 4 colors
ccrainbow - 4 colors
dkrainbow - 4 colors

that's the closest groupings i could think of that hovered around 5 each. alternatively zombies could be a thing to themselves which would make 4 colors and some other colors can be thought up for another set.

not sure how the styles should be done tho.

**Comment by lemoness** [comment]
6 is fine - and those groupings seem pretty good! I'm thinking basic dyes
always (a la rainbow skin), pastels for the spring event... as for the
others, here's some brainstorming:
1. Looking at it again, we might want to consolidate the rainbows. Do you
   have any thoughts on this?
   Could be released during summer event?
2. Pet-based colors + fire - unlocked upon completing Mount Master? Would
   take a long time. Beast Master? Both? Alternatively, could be Halloween
   hair, because of the Zombie inclusion, and fire works well.
   Dress-As-Your-Pet for Halloween, heh!

What do we feel about hairstyles? I think we should group then, but they
should be always available for purchase. So the current ones are one group,
CP's are another, and mariahm's are a third?

**Comment by crystalphoenix** [comment]
hm... consolidating all of the rainbows would make a set of 12. would that be too large? if so, what about just including the regular and cc rainbow colors?
summer sounds like an appropriate time :)

hm, my concern with grouping hairstyles like that would be distinguishing which layers each piece belongs to. right now each layer has its own group. but mariahm's set has a bang included too.
with the way the current avatar equip system is laid out, mixing different layer pieces in the same set wouldn't be a good idea. it would be difficult to tell what pieces can be worn together. if there was a separate "shop" area and a "dressing room" area it could probably work. "shop" could have sets by what can be bought together, while the "dressing room" could organize all of the pieces available to you by layer as you choose what you want to use. 

@lemoness i have some questions on what will be used,so i don't spend time on creating those files if i don't have to
1. will the version of bang 3 without the black outline on the bottom be used? 
2. i noticed that the asymmetric styles currently available only have a version on one side. should i do the same for the other buns and tails? if so, should they also be on the right side?

**Comment by ghost** [comment]
Hope you both had a good Christmas, or whichever holiday you celebrate :)

rainbows: pride week might be a very good time to release them. (june 20th, ish). If going that way I could do some of the other flags as well (bi & trans). -- also if releasing them this way, that should be just the "regular" rainbow, not the CC or dark.
To be honest, the only set where I personally really like the vertical stripe rainbow pattern is in the pastel set. The horizontal matches up with the skin thematically, though I didn't check how the colors fall against it. And I would only pick one of the curved sets, but not a mix of the two, the colorations for the hairstyles are set up to work with the bangs from that set.
...relooking at the file I also think the filters I had on the dark-rainbow accidentally were hidden when I exported the most recent file, they look the same as the regular. I can re-upload if you want to use them.

I'd also consolidate the zombie set, picking between the yellow eyes/no effect on eyes sets.

Easter for the pastels makes sense. Though it does make me want to try some ridiculous patterns ;)

grouping of styles: if you want to stick with the way things are arranged now, I personally have no problem mixing my pieces with @crystalphoenix's, if its OK with her, and having a set of "bang layer/above bang layer" styles and then a regular set or two.
with the topknot, the two spike styles, the mohawk, the afro bangs, and possibly the big afro redone to cover the outlines you've got a set of roughly the right size.
the other styles come out to the right number if you go with a right hand only version for the asymetric options.  (but it does split the afros across two groups)

**Comment by lemoness** [comment]
I like the shop vs. dressing room idea - in fact, somebody was requesting a
way to try on clothes and hairstyles for your avatar, so that might be a
useful tool.

@crystalphoenix -

I think the black outline is here to stay, since it's from the original BQ
art... I know it doesn't quite match, but we've never had any complaints.

I think it would be an easy way to consolidate if the "individual
hairstyles" were only on the right.

@mariahm, I think your ideas about consolidation also seem pretty good - I
would like to trim down the rainbow hair set from 12 to something more
reasonable, especially since there's only one rainbow skin.

**Comment by crystalphoenix** [comment]
hey guys, sorry i haven't given an update on this. settling into a new job has been taking priority.
been chipping away at the files in between things but don't think i'll be able to put things in until the weekend. thought i'd drop a note here until then ^^;

**Comment by lefnire** [comment]
no worries @crystalphoenix , we've got a lot keeping us busy so take your time :)

**Pull request merged**
