### PR TITLE
off-hand to shield-hand in gear.json and questsContent.json

### PR DESCRIPTION
**Pull request by nataliechan**
I haven't confirmed this works on the site because I'm still trying to figure out how to add weapons - db.users.update({_id: 'bec4aa9c-0be1-4131-aa47-a1bc40d4a910''}, {$set: {"items.gear.owned":"questGoldenknight3DropWeapon": true}} didn't seem to work, I probably need to add the weapon before I set it to true? But I figured this was a simple enough fix that I'd submit it for now and figure out the testing tomorrow/later this week.

### CODE REVIEW

**Comment by deilann** [comment]
Were your quotes mismatched like that?

**Comment by deilann** [comment]
What's your UUID?

**Comment by nataliechan** [comment]
yes, yes they were >< thanks for pointing that out. now I've got the weapon in 'owned', just need to figure out how to set it to true and put the original warrior sword back! that's for tomorrow though. 

my UUID is c53348e8-2332-4a61-ae09-5a1b97b88607 (:

**Comment by deilann** [comment]
tier++!

**Pull request merged**
