### PR TITLE
add markdown as angular filter

### PR DESCRIPTION
**Pull request by negue**

### CODE REVIEW

**Comment by negue** [comment]
@lefnire @paglias It is good to merge? Since I would only add this filter.

**Comment by Alys** [comment]
It's probably a really good idea to wait a few days until the server settles down before we make more changes to the site.

From the sounds of the latest updates, @lefnire is pretty busy at the moment and might not have time to advise.

**Comment by paglias** [comment]
@negue sorry, what's the reason about that? I mean we already have the directive

**Comment by negue** [comment]
You can't use a directive inside a "attribute binding".

**Comment by paglias** [comment]
:+1: if it's not a problem let's wait for the rest to be solved as @Alys suggested before merging, for me it's ok to merge it when we can

**Comment by negue** [comment]
Of course! First all bugs must be solved before we can add more features. :)

**Comment by lefnire** [comment]
For my own, I don't want to be the bottleneck of PRs getting merged as I struggle with memleak + mongoose `defaul:{}` stuff. Up to y'all, sounds like the three of you agree on waiting - but I'd personally say "hey, keep 'em mergin! I'll be back"

**Comment by negue** [comment]
I'll merge this tomorrow after work.

**Pull request merged**
