### PR TITLE
Streamlined "Confers no benefit" placements

### PR DESCRIPTION
**Pull request by gitte-k**
Streamlined the placement of "Confers no benefit" so it doesn't change location between similar sentences.

### CODE REVIEW

**Comment by crookedneighbor** [comment]
I'm all for making things consistent, but changing these files will prompt Transifex to mark these strings as needing to be translated again.

@paglias, do you think that's worth it?

**Comment by gitte-k** [comment]
Hm, true. I'm a bit obsessive about things like this, but I can see your point. Maybe wait and have it as part of a bigger launch of things to (re)translate at some point?

**Comment by crookedneighbor** [comment]
Yeah, me too. If it was up to me alone, I'd just merge it in.

**Comment by paglias** [comment]
Let's merge. I'll wait a week before updating translations
Il 14/dic/2014 17:27 "Blade Barringer" notifications@github.com ha
scritto:

**Comment by crookedneighbor** [comment]
:+1: 

Can someone notate this contribution on @lacrimae's user? The uuid is `3ecf07b0-4bea-4e6b-b0a0-4cb6e29a5699`

**Comment by Alys** [comment]
Tier ++. Thank you @lacrimae! The higher tiers become harder to earn, so you might find that for future small changes, you won't get a tier for each, but every one will be recorded to go towards your next tier.

**Comment by gitte-k** [comment]
@Alys oh wow, I really didn't expect to get a contributor tier for this... it's such a small change. But thanks nonetheless - and I think I'll prefer to "save" up for the next one anyway, as I'd feel it more of an accomplishment then :)

**Pull request merged**
