### PR TITLE
Calculate chance to drop using a slowly increasing function

### PR DESCRIPTION
**Pull request by BlackEdder**
This would address part of HabitRPG/habitrpg#1922 by giving a maximum drop chance of 75%.

The commit adds a function that increases as the chanceModifier increases till a maximum of 75%. It's based on a Monod equation https://en.wikipedia.org/wiki/Monod_equation

Feel free to ignore if this is not what you are looking for.

### CODE REVIEW

**Comment by SabreCat** [comment]
Sounds like a decent patch for the guaranteed-drops issue until a more thorough overhaul of drop chances is agreed upon and implemented.

**Comment by lefnire** [comment]
This looks good to me. I'll merge unless @paglias @Fandekasp @snicker have any objections. @BlackEdder any chance of commenting out the old, and adding a note along the lines of @SabreCat's bit above?

**Comment by SabreCat** [comment]
Speaking of such long-term things, I would love any and all commentary on my ideas over on HabitRPG/habitrpg#1922 !

**Comment by BlackEdder** [comment]
@lefnire Added some more details. Let me know if that is what you were looking for.

**Comment by lefnire** [comment]
Thanks @BlackEdder!

**Comment by BlackEdder** [comment]
I know it was only a tiny contribution, but would this earn me the contributor badge :)
My userid: 62cf3b41-a297-4dd9-aa2d-2d1e051abbde

**Comment by lefnire** [comment]
oh, of course! Sorry I didn't ask for your UUID - updated

**Pull request merged**
