### PR TITLE
Adjust golden knight (shouldn't get Jean Chalard's Tunic)

### PR DESCRIPTION
**Pull request by taldin**
Since you probably aren't supposed to get Jean Chalard's Tunic (the equipment reward from finishing the Recidivate Transformed quest) AND Mustelaine's Mashing Offhand, here's a quick fix to get rid of the line awarding the Tunic.   (Also apparently rebundles my unpicked up fix for rebuying the Main Hand Morningstar fix on my Develop branch.  Sorta oops.)

### CODE REVIEW

**Comment by lefnire** [comment]
Thanks! Uuid?

**Comment by taldin** [comment]
316dc314-29b3-4586-9ac3-386476e3a89e
Any thoughts on which way you want to go with the Mustelaine duplicate weapon issue?

**Comment by lefnire** [comment]
contrib.lvl++, thanks! I haven't kept up on the MMM issue, but sounds it's been addressed in another thread?

**Comment by taldin** [comment]
Yep, we resolved it via Lemoness.   Wiki adjusted to match.  Thanks for the +!

**Pull request merged**
