### PR TITLE
German Translation Basis

### PR DESCRIPTION
**Pull request by luveluen**
The German translation (from scratch) does still have rough edges, mainly some vocabulary, that is not, yet, agreed on.
I would love to discuss that with someone to establish a set vocabulary to use here and in the German Wikia (so far it all fits together, because it is all done by me...but that can quickly change...)

This certainly still needs some correction for spelling mistakes that I overread.
But for someone to do that it needs to be merged already.

I created the "de" folder since it was not there, yet.
Then I copied the content of the English files, translated them and then uploaded the content to newly created .json files named correspondingly.

Also:
User ID
be0d25d1-9e71-400d-9d78-7c06647f419f

I can do other translations as well, but I don't want to hog all the credit so we will see what is needed in the future.

Process Sinza-s edit first, I can tweak this commit in case something does not fit together.

### CODE REVIEW

**Comment by paglias** [comment]
Could you update it with https://github.com/HabitRPG/habitrpg-shared/commit/63f691b00d8a004a8a326c69327b5d6db58951dd#diff-588880ffc6e95123c361e7fc950d1f72R15 and https://github.com/HabitRPG/habitrpg-shared/commit/619d254cc007d5ca58d559513beb2b4f5f688129#diff-cbdbc2cb085f9413c97b6adf9ef73a9dR42?

**Comment by colegleason** [comment]
Lol, I went to the commit summary and everything was in English. I was confused. then I realized Chrome automatically translated the page from German to English.

**Comment by luveluen** [comment]
I think I already did update it (the last commit, click on the "...")
Once it is pulled I will have someone read through it, swap notes and we will discuss the vocabulary I ended up using ("Habits" is easy enough to translate, but "dailies" and "To-Do" has no German translation per se... and if I write "To-Do" in German I better commit anonymously, because otherwise I will get lynched at university).

**Comment by luveluen** [comment]
Haha @colegleason , that is tricky, but a great feature.

**Comment by paglias** [comment]
@luveluen as soon as habitrpg-shared is deployed, german will be avalaible, the first language :)) Thanks!

**Pull request merged**
