### PR TITLE
Remove challenges when reset (habitrpg - Bug #4090)

### PR DESCRIPTION
**Pull request by TheCthulhuKid**
Sets challenges to an empty array when reset is implemented

### CODE REVIEW

**Comment by TheCthulhuKid** [comment]
But the error had nothing to do with my change:

image

**Comment by Alys** [comment]
Unfortunately there's more to removing challenges than setting that array to empty. The database contains a "challenges" collection with data like the sample below. The user would need to be removed from the members array in the challenge's object. If that isn't done, then when the user looks at the challenges page, it looks like they're still signed up to the challenges.

We also need to consider what happens when the user is the creator of a challenge. After a reset, they must still be able to administer the challenge. In that case, it's probably best to not remove them from the challenge at all.

Challenge tags should also be removed from the user's account (except when they're the challenge owner?). 

If you'd like to keep working on this, please do go ahead. To the best of my knowledge no one else is working on it. If you'd prefer not to, or if you won't be able to for a while, then it might be best if this PR is closed.

```
[
    {
        "_id": "709905d2-0068-4e55-ab2a-680bd552714a",
        "name": "ch 1",
        "description": "ch 1",
        "leader": "82467c2f-894e-4417-ab77-4b9acbc6bf87",
        "group": "f8c372ff-829d-4892-a7be-887d4ccc9caf",
        "shortName": "ch 1",
        "prize": 1,
        "memberCount": 0,
        "members": [
            "82467c2f-894e-4417-ab77-4b9acbc6bf87"
        ],
        "timestamp": {
            "$date": "2014-10-10T10:07:42.050+0000"
        },
        "todos": [
            {
                "text": "ch 1 a",
                "attribute": "str",
                "priority": 1,
                "value": 0,
                "notes": "",
                "dateCreated": {
                    "$date": "2014-10-10T10:08:06.779+0000"
                },
                "id": "5f63e76a-6106-435b-bcd9-ae0e6227f7f4",
                "checklist": [],
                "collapseChecklist": false,
                "completed": false,
                "type": "todo"
            }
        ],
        "__v": 0
    }
]
```

**Comment by TheCthulhuKid** [comment]
I will give it a go =)

**Comment by viktoriyavulfson** [comment]
@gileadslostson did you manage to make it work? if not, can I give it a go?

**Comment by TheCthulhuKid** [comment]
@ViktoriyaSavkina please do so! My son is ill and I have had no time at all. Sorry!

**Comment by crookedneighbor** [comment]
Going to close this. @gileadslostson and @ViktoriyaSavkina We're going to be migrating the shared repo into the main repo, so feel free to work on this if you'd like, but there's going to be a big transition soon (hopefully).

**Pull request closed without merging**
