### PR TITLE
adding mechanic to count previously owned pets

### PR DESCRIPTION
**Pull request by deilann**
changes hatched pets from 0 to -1

### CODE REVIEW

**Comment by deilann** [comment]
Oh, right, and this also changes it so you can't feed pets if you own the requisite mount

**Comment by lefnire** [comment]
Elegant, @deilann. Elegant.

**Comment by deilann** [comment]
And this, children, is why you should never sleep.

**Comment by lefnire** [comment]
[Here's what](http://gyazo.com/657d3b8dd15daf475a68542508e2a3a2) it looks like btw. Wont' see it until next push, unfortunately the new deployments will probably be pretty staggered since the `HabitRPG/develop`=>`lefnire/habitrpg-private` merge (added step for premium accounts) adds a bunch of overhead. I hope to peg down a better workflow sooner than later

**Comment by deilann** [comment]
I can't tell if that's slightly too light, or it's my blistering headache.
What does 15% look like?

**Comment by lefnire** [comment]
[15](http://gyazo.com/f539eb276663c41996baaeba02b57a40) [25](http://gyazo.com/fd153905254edc5ba794c899d7a4fedb)

**Comment by deilann** [comment]
15 looks good to me, but part of color deficiency is things sometimes being
further "dimmed" than they are, especially later in the day. So I'd get
another pair of eyes on it.

**Pull request merged**
