### PR TITLE
innText update of groups.json

### PR DESCRIPTION
**Pull request by wc8**
String change. Adds new inn message as a first step toward #3627. This is combination of the proposed messages I proposed there, and incorporates the user's name:

"How's your stay in the Inn, <%= name %>? To protect you, your daily list is frozen. Your checkmarks won't be processed or cleared until tomorrow (the day after you check out). Be careful, if your party's in a Boss Battle, their misses will hurt you! Also, you won't hurt the boss. Ready to leave? Check out."

### CODE REVIEW

**Comment by deilann** [comment]
Why did you close and delete this?

**Comment by wc8** [comment]
there was a problem Travis failed, so I [redid it.](https://github.com/HabitRPG/habitrpg-shared/pull/230)

**Comment by deilann** [comment]
Chances are, that travis fail was _not_ you, but me. All builds are failing
because I haven't fixed the tests.

**Comment by wc8** [comment]
Oh, ok. I thought it might be the string including the username. So I did #230 without it.

**Comment by wc8** [comment]
Thanks. If the username can be included via <%= name %> I think that's better. Should I close #230 and reopen this one?

**Comment by deilann** [comment]
I already merged #230, you what you'll actually want to do is make a new PR, just adding the username!

**Comment by wc8** [comment]
Thanks.

**Pull request closed without merging**
