### PR TITLE
More unit tests

### PR DESCRIPTION
**Pull request by djuretic**

### CODE REVIEW

**Comment by paglias** [comment]
We could also add travisci to this repo.... so every pull request is checked against these tests

**Comment by lefnire** [comment]
@djuretic YES YES YES! You are my new favorite person, long has been our need for unit tests.

**Comment by djuretic** [comment]
@paglias Good idea! I can create the `.travis.yml` file if needed.

**Comment by paglias** [comment]
Fantastic! Then @lefnire needs to activate it on travis-ci.org and we'll be
ready!

2013/9/29 djuretic notifications@github.com

> @paglias https://github.com/paglias Good idea! I can create the
> .travis.yml file if needed.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/HabitRPG/habitrpg-shared/pull/23#issuecomment-25321130
> .

## 

Matteo Pagliazzi - paglias.net

**Comment by djuretic** [comment]
Done, check out #24

**Pull request merged**
