### PR TITLE
More egg drop text improvements

### PR DESCRIPTION
**Pull request by SabreCat**
- Typo fix ("it's" to "its")
- Add a descriptive property "adjective" to pet objects
- Make the egg drop text dynamic, in a similar fashion to the way potion drop text already works

### CODE REVIEW

**Comment by lefnire** [comment]
@SabreCat good idea! does this work? (have you had a chance to test it locally per chance?)

**Comment by paglias** [comment]
I didn't tested it locally but I'm quite sure it's going to work

**Comment by SabreCat** [comment]
Indeed, I tested this one out before committing, back whenever that was ^.^
I'd assumed it was kept on hold since it changes pet data structure a bit.

**Comment by lefnire** [comment]
oh wow, it was 3 months ago! I'm a failure :( :( I think it's actually a safe change to pet schema, since the pet schema is used so rarely (once pet is hatched, it's only referred to by string)

**Comment by lefnire** [comment]
oh, i'll need to point it to develop. i'll hit when when i have a moment

**Comment by SabreCat** [comment]
...did we end up deciding against this one? Let me know if I should close.

**Comment by lefnire** [comment]
don't close yet, i want to keep this but I want to merge mounts first. It may break this PR and I'll just do a manual merge.

**Comment by lefnire** [comment]
had to manually splice in, sorry @SabreCat: https://github.com/HabitRPG/habitrpg-shared/commit/30b19b5e7d8cf3b5bebd8d0d43528f4440928c3d . This won't go out till the next habitrpg#develop commit & push.

**Pull request closed without merging**
