### PR TITLE
Issue4454habitrpg

### PR DESCRIPTION
**Pull request by melissamcewen**
I added the immediate use variable

### CODE REVIEW

**Comment by crookedneighbor** [comment]
Awesome. Can you add it to the opaque potion and nye card spells as well?

**Comment by melissamcewen** [comment]
@crookedneighbor oh yeah, those haha. Added.

**Comment by melissamcewen** [comment]
Would it also make sense to add info about it costing coins in the description?

**Comment by crookedneighbor** [comment]
I don't think so. I think it'd be redundant to include it, because the only places you see it are in the rewards column, where it's very obvious that it costs 5 gold:

screen shot 2015-01-01 at 4 30 18 pm

And the seasonal shop for New Year Cards:

screen shot 2015-01-01 at 4 30 29 pm

**Comment by melissamcewen** [comment]
ah mine didn't have the coin but I then realized my shared repo was out of date

**Pull request merged**
