### PR TITLE
Shifted the panda skeleton head for issue #3954. 

### PR DESCRIPTION
**Pull request by ebiagogo**
Had to open and save quest_atom1.png because I was getting an error running 'grunt sprite'. Committing the generated spritesmithX.png files in dist as well.

### CODE REVIEW

**Comment by crookedneighbor** [comment]
Can you tell me what error you were getting with `grunt sprite`?

**Comment by crookedneighbor** [comment]
Never mind, I see your comment now in https://github.com/HabitRPG/habitrpg/issues/3954

**Comment by crookedneighbor** [comment]
@ebiagogo Sorry that took so long. Can you post your user id here? It can be found in [settings > api](https://habitrpg.com/#/options/settings/api)

Oh, I just realized I never confirmed whether or not you gave arts permissions for your change. Did you follow the instructions and send out the email to @lemoness and the rest? If not, I'll have to revert the commit.

**Comment by ebiagogo** [comment]
I submitted the arts permissions before I submitted the pull request, so that should be all set. 

ebe34b97-b3f0-4dc6-8987-0db414042619

**Comment by crookedneighbor** [comment]
Awesome, could someone with mod permissions on the site notate this?

**Comment by Alys** [comment]
Tier++.

Thank you @ebiagogo. Note that the higher tiers require more effort than the lower ones, so if you make any small changes from now on, you might find that they won't grant you an extra tier immediately, but they will be noted as partial credit towards a tier. There's a bit of information about that at [Contributor Rewards](http://habitrpg.wikia.com/wiki/Contributor_Rewards) but do ask if you have questions.

**Comment by paglias** [comment]
@Alys can we give Blade the ability to award badges? Is it enough to check
the admin chexkbox in the reward user box or there's something more to do?
Il 31/dic/2014 00:02 "Alice Harris" notifications@github.com ha scritto:

**Comment by crookedneighbor** [comment]
@paglias I believe I need to be made a level 8 contributor to do it, but that also makes me mod. Which is cool with me, but I understand if anyone doesn't want that.

I believe direct db manipulation can give me the isAdmin = true attribute, but the only difference between me and the other mods would be that I'd retain my light blue label instead of getting the dark blue label. So, whatever y'all want is fine.

**Comment by Alys** [comment]
@paglias It's a question for @lemoness. @crookedneighbor is correct about the technical details.

**Comment by Alys** [comment]
Note that if your only reason is so that Blade doesn't need to keep asking us to give tiers, then it's not really necessary that he asks. We get all the emails from GitHub, and I read them all (as I'm sure do others), so I always see when a PR has been merged and a UUID has been provided. Asking us to give tiers isn't a necessary step.

**Comment by crookedneighbor** [comment]
I'm just paranoid about people's contributions getting missed. If you're confident that you won't miss a PR that I merged and closed, I don't need to comment about it.

**Comment by Alys** [comment]
Yes I am confident.

**Comment by paglias** [comment]
My fault, I though some mods were level 7
Il 31/dic/2014 01:17 "Alice Harris" notifications@github.com ha scritto:

**Pull request merged**
