### PR TITLE
Made Clover-steel Helmet boost strength instead of perception; increased...

### PR DESCRIPTION
**Pull request by PeterHatch**
... cost of Hook Claws to match Ninja-to and Ski.

### CODE REVIEW

**Comment by PeterHatch** [comment]
Also removed duplicate setting of specialClass on the spring shields.

**Comment by deilann** [comment]
Personally, I wouldn't change the price, as the items have already come
out. However, the clover-steel helmet thing does need to be fixed as well
as the dupe setting. Can you split the commits so I can merge them
separately and see what the cofounders think about changing prices?

**Comment by PeterHatch** [comment]
Not familiar enough with Git to know of a way to split the commit, so I just added a commit that undoes the change to the price - hopefully that works?

**Comment by deilann** [comment]
Awesome, thanks. This is actually a much more simple solution.

**Comment by deilann** [comment]
lvl++! Happy green!

I'm gonna arbitrarily say level 4 would be 4 or so of the smaller commits, but if any one who hands out more contrib levels than me disagrees, feel free to speak up. :P

**Comment by PeterHatch** [comment]
Thanks!

**Comment by lefnire** [comment]
This @PeterHatch character is on the rise!

**Pull request merged**
