### PR TITLE
Fixed a typo ("whe" --> "when")

### PR DESCRIPTION
**Pull request by Atomk**

### CODE REVIEW

**Comment by paglias** [comment]
:+1: uuid?

**Comment by Atomk** [comment]
d8fc8d8b-a10f-416a-b089-587db2af9e4d
I did not fixed anything big anyway :)

**Comment by paglias** [comment]
@Omnomnobot oh you're already level 4 and I think that at this point new levels require more contributions than the previous one, right @deilann ?

**Comment by deilann** [comment]
Yeah, but I still record them, to be taken into account when it's getting
closer to lvl++ time.

On Mon, Jun 30, 2014 at 12:38 PM, Matteo Pagliazzi <notifications@github.com

**Comment by Atomk** [comment]
Seems legit, thank you!

**Pull request merged**
