### PR TITLE
suggested fix for adding "special" pets 

### PR DESCRIPTION
**Pull request by snicker**
so that the list does not have to be duplicated multiple times. the user model can be updated in `habitrpg` to pull from here instead of hard coding it

I couldn't actually test this, so I didn't want to merge straight away... could someone else verify this works? @paglias, @lefnire

### CODE REVIEW

**Comment by snicker** [comment]
Sorry about that one, it should be passing now!

**Comment by paglias** [comment]
@snicker the code is ok, you just need to run `grunt` in order to compile the javascript file & commit it to github - great!

**Comment by snicker** [comment]
Ahhhhhhhhhhhhhh

**Comment by snicker** [comment]
Alrighty, this should all be peachy now. Merging!

**Comment by lefnire** [comment]
pushed, thanks @snicker !

**Pull request merged**
